##############################################################################################################
#Thank you for using my plugin, if you could leave your opinion on spigot I would be very happy :)
#Pugin will often be updated following the newest minecraft version and new Features will get added.
#If you need any help join plugin's discord server: https://discord.gg/d5Np9C8KBa
# -Diamond_Iq :D
##############################################################################################################


Economy-Enabled: false    #Do you want to connect to economy? !!!"Vault" and "economy" plugin needed!!!

##############################################################################################################
#vanish
join-and-leave-message-on-vanish: true        #Do you want to say "Player left/joined the game" when a player uses vanish?
join-message-on-vanish: '&e{player} joined the game'    #Optional Variables: {luckpermsprefix} ,{luckpermssuffix}
leave-message-on-vanish: '&e{player} left the game'

##############################################################################################################
#launch
launch-power: 5
launch-cost: 500    #!!!Enable Vault Economy for this to work!!!

#lightning
lightning-cost: 300   #!!!Enable Vault Economy for this to work!!!

#no-internet
no-Internet-cost: 50  #!!!Enable Vault Economy for this to work!!!

#set on fire
set-on-fire-cost: 100 #!!!Enable Vault Economy for this to work!!!

#nausea
nausea-cost: 200  #!!!Enable Vault Economy for this to work!!!

#make player 2x slower
slow-cost: 500    #!!!Enable Vault Economy for this to work!!!

#fake sounds
sound-volume: 500
sound-pitch: 1
fake-sound-cost: 50   #!!!Enable Vault Economy for this to work!!!

#fake ban
fakeban-message: '&cYou Have been banned From This Server'    #Option Variable {player} = The person trolling (For ex. "&cYou have been banned by {player}")
fake-ban-cost: 400    #!!!Enable Vault Economy for this to work!!!

#NoGravty
no-gravity-cost: 300    #!!!Enable Vault Economy for this to work!!!

#cobweb player
cobweb-cost: 500    #!!!Enable Vault Economy for this to work!!!
cobweb-time-after-disappear: 20 #in seconds

#Time warp
time-warp-cost: 300   #!!!Enable Vault Economy for this to work!!!
time-warp-time: 10 #In seconds

#Explosive apple
explosive-apple-cost: 500   #!!!Enable Vault Economy for this to work!!!
apple-explosion-power: 3

#meteor
meteor-explosion-power: 8
meteor-cost: 400    #!!!Enable Vault Economy for this to work!!!

#Patata
patata-time: 20 #In seconds, Time after the inventory will be back to its previous state
patata-cost: 300    #!!!Enable Vault Economy for this to work!!!

#Spawn Mobs
Mob-options:
  Zombie:
    cost: 50
  Skeleton:
    cost: 70
  Spider:
    cost: 40
  Chicken-Jokey:
    cost: 100
  Ravager:
    cost: 200
  Enderman:
    cost: 100
  Warden:
    cost: 400
  Iron-Golem:
    is-angry: true
    cost: 250
  Creeper:
    cost: 70
  Charged-Creeper:
    cost: 100
  Snowman:
    is-angry: true
    cost: 150
  Blaze:
    cost: 100
  Axolotl:
    Variant: 'BLUE'
    cost: 100
  Allay:
    cost: 50
  Sniffer:
    cost: 50
  Camel:
    cost: 100

#fake message
fake-messages-cost: 200   #!!!Enable Vault Economy for this to work!!!
chat-format: '<{player}> {message}'   #The fake message will be sent in this format, !!!Make Sure to use these variables: {player} and {message}!!! Optional Variables: {luckpermsprefix} ,{luckpermssuffix}
messages:
  - 'Message number 1'    #Messages Will be chosen randomly
  - 'Message number 2'    #You can have as many messages as you want
  - 'Message number 3'
  - 'Message number 4'
  - 'Message number 5'

#1 heart
one-heart-cost: 500   #!!!Enable Vault Economy for this to work!!!

#Cancel Block Breaks
Cancel-Block-Breaks-cost: 400   #!!!Enable Vault Economy for this to work!!!
Cancel-Block-Breaks-time: 30    #In seconds
Cancel-Block-Breaks-CustomMessage:
  enabled: false
  message: '&cOops, It seems you can not break this :(' #You can use hexadecimals e.g #FFFFFFMessage...

#Cage
cage-disappear-time: 30 #In seconds

#Swap Lava with Water
swapLavaWater-cost: 500     #!!!Enable Vault Economy for this to work!!!

#HOT POTATO
hotpotato-burn-time: 30 #In seconds
hotpotato-cost: 500     #!!!Enable Vault Economy for this to work!!!





##############################################################################################################





