name: DiaTroll
version: '${project.version}'
main: me.diamond.trollplugin.TrollPlugin
api-version: 1.19
authors: [ Diamond_Iq ]
commands:
  troll:
    description: Opens The Troll Gui
    usage: /<command> <player>
  vanish:
    description: Vanishes you from other players
    usage: /<command> <player>
    aliases: v
  diatroll:
    description: The main command
permissions:
  diatroll.teleport:
    description: Teleport To player
  diatroll.admin:
    description: Admin Permissions
  diatroll.troll:
    description: Allow Troll Gui
  diatroll.reload:
    description: Reload Config
  diatroll.help:
    description: /diatroll help command
  diatroll.vanish:
    description: Allow /vanish
  diatroll.troll.launch:
    description: Launch player into the air
  diatroll.troll.lightning:
    description: Hit the player with lightning
  diatroll.troll.nointernet:
    description: Kick player for having no Internet
  diatroll.troll.fire:
    description: Set player on fire troll
  diatroll.troll.nausea:
    description: Give Player Nausea effect
  diatroll.troll.slow:
    description: Make player 2x slower
  diatroll.troll.wardensound:
    description: Play warden sound for player
  diatroll.troll.fakeban:
    description: Kick player, imitating a ban
  diatroll.troll.togglegravity:
    description: Toggle gravity of the player
  diatroll.troll.creepersound:
    description: Play creeper explosion sound for the player
  diatroll.troll.cobweb:
    description: Surround player with cobwebs
  diatroll.troll.timewarp:
    description: Time warp player a few seconds backwards
  diatroll.troll.explosiveapple:
    description: Give player an explosive apple
  diatroll.troll.meteor:
    description: Summon meteor above player
  diatroll.troll.patata:
    description: Replace every item in player's inventory, and undo after a certain amount of time
  diatroll.troll.spawnmobs:
    description: Spawn mobs near player
  diatroll.troll.fakemessage:
    description: Send a fake message from the player
  diatroll.troll.oneheart:
    description: Set the player's max health to 2 for 1 minute
  diatroll.troll.cancelblockbreak:
    description: Cancel Block Breaks for a certain amount of time for the player
  diatroll.troll.cage:
    description: Trap player in an unbreakable cage
  diatroll.troll.swaplavawater:
    description: Swap water with lava for target
  diatroll.troll.hotpotato:
    description: Give target a HOT POTATO
  diatroll.troll.lowerreach:
    description: Lower maximum reach for target
  diatroll.troll.spawnmobs.zombie:
    description: Spawn zombie
  diatroll.troll.spawnmobs.skeleton:
    description: Spawn skeleton
  diatroll.troll.spawnmobs.spider:
    description: Spawn spider
  diatroll.troll.spawnmobs.chickenjokey:
    description: Spawn chicken jokey
  diatroll.troll.spawnmobs.ravager:
    description: Spawn ravager
  diatroll.troll.spawnmobs.enderman:
    description: Spawn enderman
  diatroll.troll.spawnmobs.warden:
    description: Spawn warden
  diatroll.troll.spawnmobs.irongolem:
    description: Spawn iron golem
  diatroll.troll.spawnmobs.creeper:
    description: Spawn creeper
  diatroll.troll.spawnmobs.chargedcreeper:
    description: Spawn charged creeper
  diatroll.troll.spawnmobs.snowman:
    description: Spawn snowman
  diatroll.troll.spawnmobs.blaze:
    description: Spawn blaze
  diatroll.troll.spawnmobs.axolotl:
    description: Spawn axolotl
  diatroll.troll.spawnmobs.allay:
    description: Spawn allay
  diatroll.troll.spawnmobs.sniffer:
    description: Spawn sniffer
  diatroll:troll.spawnmobs.camel:
    description: Spawn camel
